// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718155858_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Industrial Equipment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Packaging"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1200 Market Street, Suite 800",
                            City = "New York",
                            Country = "USA",
                            Email = "purchasing@alnoortrading.com",
                            Name = "Al Noor Trading Co.",
                            Phone = "+1-212-555-0148",
                            TaxId = "US-TAX-100245"
                        },
                        new
                        {
                            Id = 2,
                            Address = "44 King William Street",
                            City = "London",
                            Country = "UK",
                            Email = "accounts@bluewaveretail.com",
                            Name = "BlueWave Retail Ltd.",
                            Phone = "+44-20-5550-2211",
                            TaxId = "GB-TAX-778845"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Business Bay Tower 18",
                            City = "Dubai",
                            Country = "UAE",
                            Email = "billing@horizonconstruction.com",
                            Name = "Horizon Construction LLC",
                            Phone = "+971-4-555-0198",
                            TaxId = "AE-TAX-442110"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Procurement"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "layla.hassan@erpco.com",
                            FirstName = "Layla",
                            HireDate = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hassan",
                            Phone = "+1-212-555-0101",
                            Position = "Sales Executive",
                            Salary = 14500m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "omar.farouk@erpco.com",
                            FirstName = "Omar",
                            HireDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Farouk",
                            Phone = "+1-212-555-0102",
                            Position = "Operations Supervisor",
                            Salary = 16800m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "rania.khaled@erpco.com",
                            FirstName = "Rania",
                            HireDate = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Khaled",
                            Phone = "+1-212-555-0103",
                            Position = "Finance Specialist",
                            Salary = 15500m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "tarek.youssef@erpco.com",
                            FirstName = "Tarek",
                            HireDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Youssef",
                            Phone = "+1-212-555-0104",
                            Position = "Procurement Officer",
                            Salary = 13200m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DueDate = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Status = "Sent",
                            TotalAmount = 2004m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DueDate = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            PaidAt = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TotalAmount = 1100m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DueDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Status = "Draft",
                            TotalAmount = 470m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceLines_TaxRate", "[TaxRate] >= 0 AND [TaxRate] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laser Printer - Model LP850",
                            InvoiceId = 1,
                            Quantity = 2,
                            TaxRate = 5m,
                            UnitPrice = 850m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wireless Barcode Scanner - Model WBS320",
                            InvoiceId = 1,
                            Quantity = 1,
                            TaxRate = 5m,
                            UnitPrice = 320m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ergonomic Office Chair - Model OC240",
                            InvoiceId = 2,
                            Quantity = 4,
                            TaxRate = 0m,
                            UnitPrice = 240m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Heavy Duty Carton Box Pack",
                            InvoiceId = 2,
                            Quantity = 4,
                            TaxRate = 0m,
                            UnitPrice = 35m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Industrial Sensor - Model IS180",
                            InvoiceId = 3,
                            Quantity = 2,
                            TaxRate = 15m,
                            UnitPrice = 180m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ShippingAddress = "1200 Market Street, Suite 800, New York, NY",
                            Status = 2,
                            TotalAmount = 2004m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ShippingAddress = "44 King William Street, London",
                            Status = 3,
                            TotalAmount = 1100m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "MobilePayment",
                            ShippingAddress = "Business Bay Tower 18, Dubai",
                            Status = 1,
                            TotalAmount = 470m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Orders.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines", t =>
                        {
                            t.HasCheckConstraint("CK_OrderLines_DiscountPercentage", "[DiscountPercentage] >= 0 AND [DiscountPercentage] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 0m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 850m
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 5m,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 320m
                        },
                        new
                        {
                            Id = 3,
                            DiscountPercentage = 0m,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 4,
                            UnitPrice = 240m
                        },
                        new
                        {
                            Id = 4,
                            DiscountPercentage = 0m,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 4,
                            UnitPrice = 35m
                        },
                        new
                        {
                            Id = 5,
                            DiscountPercentage = 0m,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 180m
                        },
                        new
                        {
                            Id = 6,
                            DiscountPercentage = 0m,
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 55m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CostPrice = 620m,
                            Name = "Laser Printer",
                            ReorderLevel = 5,
                            Sku = "PRN-LP850",
                            StockQuantity = 18,
                            UnitPrice = 850m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CostPrice = 145m,
                            Name = "Ergonomic Office Chair",
                            ReorderLevel = 10,
                            Sku = "CHR-OC240",
                            StockQuantity = 30,
                            UnitPrice = 240m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CostPrice = 210m,
                            Name = "Wireless Barcode Scanner",
                            ReorderLevel = 6,
                            Sku = "SCN-WBS320",
                            StockQuantity = 14,
                            UnitPrice = 320m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CostPrice = 110m,
                            Name = "Industrial Sensor",
                            ReorderLevel = 12,
                            Sku = "SNS-IS180",
                            StockQuantity = 40,
                            UnitPrice = 180m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CostPrice = 18m,
                            Name = "Heavy Duty Carton Box Pack",
                            ReorderLevel = 50,
                            Sku = "BOX-HD035",
                            StockQuantity = 150,
                            UnitPrice = 35m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CostPrice = 30m,
                            Name = "Safety Helmet",
                            ReorderLevel = 20,
                            Sku = "SFT-HM055",
                            StockQuantity = 80,
                            UnitPrice = 55m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 5,
                            UnitCost = 620m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            PurchaseOrderId = 1,
                            Quantity = 10,
                            UnitCost = 210m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            PurchaseOrderId = 2,
                            Quantity = 8,
                            UnitCost = 145m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 5,
                            PurchaseOrderId = 2,
                            Quantity = 40,
                            UnitCost = 18m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 4,
                            PurchaseOrderId = 3,
                            Quantity = 10,
                            UnitCost = 110m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            PurchaseOrderId = 3,
                            Quantity = 20,
                            UnitCost = 30m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpectedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedDelivery = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Received",
                            SupplierId = 1,
                            TotalAmount = 5200m
                        },
                        new
                        {
                            Id = 2,
                            ExpectedDelivery = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            SupplierId = 2,
                            TotalAmount = 1880m
                        },
                        new
                        {
                            Id = 3,
                            ExpectedDelivery = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Draft",
                            SupplierId = 3,
                            TotalAmount = 1700m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator",
                            Permissions = "[\"Users.Read\",\"Users.Write\",\"Orders.Read\",\"Orders.Write\",\"Reports.Read\",\"Reports.Write\"]"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales Manager",
                            Permissions = "[\"Customers.Read\",\"Customers.Write\",\"Orders.Read\",\"Orders.Write\",\"Invoices.Read\"]"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warehouse Clerk",
                            Permissions = "[\"Products.Read\",\"PurchaseOrders.Read\",\"PurchaseOrders.Write\",\"Inventory.Update\"]"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Global Tech Distributors",
                            ContactName = "Maya Peterson",
                            Email = "sales@globaltechdist.com",
                            PaymentTerms = "Net 30",
                            Phone = "+1-646-555-0133"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Metro Office Supply",
                            ContactName = "Daniel Cooper",
                            Email = "orders@metroofficesupply.com",
                            PaymentTerms = "Net 15",
                            Phone = "+44-20-5550-3344"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Prime Industrial Parts",
                            ContactName = "Nadia Rahman",
                            Email = "procurement@primeindustrialparts.com",
                            PaymentTerms = "Due on receipt",
                            Phone = "+971-4-555-0220"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "omar.saleh@erpco.com",
                            FirstName = "Omar",
                            LastName = "Saleh",
                            PasswordHash = "$2a$11$k5X4wQb3G4z7kQv8Ff9M2O1hQ2rM5g7uN6p7v8w9x0y1z2a3b4c5d",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.ibrahim@erpco.com",
                            FirstName = "Sara",
                            LastName = "Ibrahim",
                            PasswordHash = "$2a$11$g2H7nQp4R8s1tV6wX9y0zAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoP",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "ahmed.nasser@erpco.com",
                            FirstName = "Ahmed",
                            LastName = "Nasser",
                            PasswordHash = "$2a$11$7uY2dK9mS1pQ4rT6vW8xZ0AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoQ",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Orders.OrderLine", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Orders.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseLine", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("PurchaseLines");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseLines");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
